name: Build Rami APK
on:
  repository_dispatch:
    types: [build_apk]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Cordova & Build
        run: |
          npm install -g cordova
          cordova create myApp com.rami.app "RamiApp"
          cd myApp
          cordova platform add android
          cordova build android --release
      - name: Save APK
        uses: actions/upload-artifact@v4
        with:
          name: Rami-App-Final
          path: myApp/platforms/android/app/build/outputs/apk/release/*.apk
